version: '3.6'
services:
  postgres:
    image: postgres:12
    restart: always
    volumes:
      - db_data_hasura_zzz:/var/lib/postgresql/data
    ports:
      - '5432:5432'
    environment:
      POSTGRES_PASSWORD: postgres_password_zzz
      PGDATA: /var/lib/postgresql/data/pgdataInternal

  graphql-engine:
    image: hasura/graphql-engine:v2.0.1
    ports:
      - '8080:8080'
    depends_on:
      - 'postgres'
    restart: always
    environment:
      CONSOLE_MODE: cli
      HASURA_GRAPHQL_DATABASE_URL: postgres://postgres:postgres_password_zzz@postgres:5432/postgres
      HASURA_GRAPHQL_ENABLE_CONSOLE: 'false' # console will run with `hasura console`
      ## enable debugging mode. It is recommended to disable this in production
      HASURA_GRAPHQL_DEV_MODE: 'true'
      HASURA_GRAPHQL_LOG_LEVEL: error
      HASURA_GRAPHQL_ENABLED_LOG_TYPES: startup, http-log, webhook-log, websocket-log, query-log
      HASURA_GRAPHQL_ADMIN_SECRET: 'admin_secret_local_zzz'
      # zzz - https://hasura.io/jwt-config/
      # HASURA_GRAPHQL_JWT_SECRET: '{"type": "RS512", "key": "zzz"}'
      HASURA_GRAPHQL_UNAUTHORIZED_ROLE: 'anonymous'
volumes:
  db_data_hasura_zzz:
